/* Generated by lx */

#include <assert.h>
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <errno.h>

#include LX_HEADER

static enum lx_abnf_token z0(struct lx_abnf_lx *lx);
static enum lx_abnf_token z1(struct lx_abnf_lx *lx);
static enum lx_abnf_token z2(struct lx_abnf_lx *lx);
static enum lx_abnf_token z3(struct lx_abnf_lx *lx);
static enum lx_abnf_token z4(struct lx_abnf_lx *lx);

#if __STDC_VERSION__ >= 199901L
inline
#endif
static int
lx_getc(struct lx_abnf_lx *lx)
{
	int c;

	assert(lx != NULL);
	assert(lx->lgetc != NULL);

	if (lx->c != EOF) {
		c = lx->c, lx->c = EOF;
	} else {
		c = lx->lgetc(lx);
		if (c == EOF) {
			return EOF;
		}
	}

	lx->end.byte++;
	lx->end.col++;

	if (c == '\n') {
		lx->end.line++;
		lx->end.saved_col = lx->end.col - 1;
		lx->end.col = 1;
	}

	return c;
}

#if __STDC_VERSION__ >= 199901L
inline
#endif
static void
lx_abnf_ungetc(struct lx_abnf_lx *lx, int c)
{
	assert(lx != NULL);
	assert(lx->c == EOF);

	lx->c = c;


	lx->end.byte--;
	lx->end.col--;

	if (c == '\n') {
		lx->end.line--;
		lx->end.col = lx->end.saved_col;
	}
}

int
lx_abnf_dynpush(void *buf_opaque, char c)
{
	struct lx_dynbuf *t = buf_opaque;

	assert(t != NULL);

	if (t->p == t->a + t->len) {
		size_t len;
		ptrdiff_t off;
		char *tmp;

		if (t->len == 0) {
			assert(LX_DYN_LOW > 0);
			len = LX_DYN_LOW;
		} else {
			len = t->len * LX_DYN_FACTOR;
			if (len < t->len) {
				errno = ERANGE;
				return -1;
			}
		}

		off = t->p - t->a;
		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->p   = tmp + off;
		t->a   = tmp;
		t->len = len;
	}

	assert(t->p != NULL);
	assert(t->a != NULL);

	*t->p++ = c;

	return 0;
}

int
lx_abnf_dynclear(void *buf_opaque)
{
	struct lx_dynbuf *t = buf_opaque;

	assert(t != NULL);

	if (t->len > LX_DYN_HIGH) {
		size_t len;
		char *tmp;

		len = t->len / LX_DYN_FACTOR;

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->a   = tmp;
		t->len = len;
	}

	t->p = t->a;

	return 0;
}

void
lx_abnf_dynfree(void *buf_opaque)
{
	struct lx_dynbuf *t = buf_opaque;

	assert(t != NULL);

	free(t->a);
}
static enum lx_abnf_token
z0(struct lx_abnf_lx *lx)
{
	int c;

	enum {
		S0, S1, S2, NONE
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx->buf_opaque);
	}

	state = NONE;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		if (state == NONE) {
			state = S0;
		}

		switch (state) {
		case S0: /* start */
			switch ((unsigned char) c) {
			case '"': state = S2; break;
			default: state = S1; break;
			}
			break;

		case S1: /* e.g. "a" */
			lx_abnf_ungetc(lx, c); return TOK_CHAR;

		case S2: /* e.g. "\"" */
			lx_abnf_ungetc(lx, c); return lx->z = z4, TOK_CS_LITERAL;

		default:
			; /* unreached */
		}

		if (lx->push != NULL) {
			if (-1 == lx->push(lx->buf_opaque, c)) {
				return TOK_ERROR;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case NONE: return TOK_EOF;
	case S1: return TOK_CHAR;
	case S2: return TOK_CS_LITERAL;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_abnf_token
z1(struct lx_abnf_lx *lx)
{
	int c;

	enum {
		S0, S1, S2, NONE
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx->buf_opaque);
	}

	state = NONE;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		if (state == NONE) {
			state = S0;
		}

		switch (state) {
		case S0: /* start */
			switch ((unsigned char) c) {
			case '"': state = S2; break;
			default: state = S1; break;
			}
			break;

		case S1: /* e.g. "a" */
			lx_abnf_ungetc(lx, c); return TOK_CHAR;

		case S2: /* e.g. "\"" */
			lx_abnf_ungetc(lx, c); return lx->z = z4, TOK_CI_LITERAL;

		default:
			; /* unreached */
		}

		if (lx->push != NULL) {
			if (-1 == lx->push(lx->buf_opaque, c)) {
				return TOK_ERROR;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case NONE: return TOK_EOF;
	case S1: return TOK_CHAR;
	case S2: return TOK_CI_LITERAL;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_abnf_token
z2(struct lx_abnf_lx *lx)
{
	int c;

	enum {
		S0, S1, S2, NONE
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx->buf_opaque);
	}

	state = NONE;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		if (state == NONE) {
			state = S0;
		}

		switch (state) {
		case S0: /* start */
			switch ((unsigned char) c) {
			case '>': state = S2; break;
			case '-':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z': state = S1; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S1: /* e.g. "a" */
			lx_abnf_ungetc(lx, c); return TOK_CHAR;

		case S2: /* e.g. ">" */
			lx_abnf_ungetc(lx, c); return lx->z = z4, TOK_NAME;

		default:
			; /* unreached */
		}

		if (lx->push != NULL) {
			if (-1 == lx->push(lx->buf_opaque, c)) {
				return TOK_ERROR;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case NONE: return TOK_EOF;
	case S1: return TOK_CHAR;
	case S2: return TOK_NAME;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_abnf_token
z3(struct lx_abnf_lx *lx)
{
	int c;

	enum {
		S0, S1, S2, NONE
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx->buf_opaque);
	}

	state = NONE;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		if (state == NONE) {
			state = S0;
		}

		switch (state) {
		case S0: /* start */
			switch ((unsigned char) c) {
			case '\n': state = S2; break;
			default: state = S1; break;
			}
			break;

		case S1: /* e.g. "a" */
			lx_abnf_ungetc(lx, c); return lx->z(lx);

		case S2: /* e.g. "\n" */
			lx_abnf_ungetc(lx, c); return lx->z = z4, lx->z(lx);

		default:
			; /* unreached */
		}

		switch (state) {
		case S0:
		case S1:
		case S2:
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx->buf_opaque, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case NONE: return TOK_EOF;
	case S1: return TOK_EOF;
	case S2: return TOK_EOF;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_abnf_token
z4(struct lx_abnf_lx *lx)
{
	int c;

	enum {
		S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, 
		S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, 
		S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, 
		S30, S31, S32, S33, S34, S35, S36, S37, S38, NONE
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx->buf_opaque);
	}

	state = NONE;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		if (state == NONE) {
			state = S0;
		}

		switch (state) {
		case S0: /* start */
			switch ((unsigned char) c) {
			case '<': state = S11; break;
			case '\t':
			case '\v':
			case '\f':
			case '\r':
			case ' ': state = S1; break;
			case ';': state = S10; break;
			case '"': state = S3; break;
			case '%': state = S4; break;
			case '=': state = S12; break;
			case '(': state = S5; break;
			case '\n': state = S2; break;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9': state = S9; break;
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z': state = S13; break;
			case '/': state = S8; break;
			case '*': state = S7; break;
			case ')': state = S6; break;
			case '[': state = S14; break;
			case ']': state = S15; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S1: /* e.g. "\t" */
			switch ((unsigned char) c) {
			case '\t':
			case '\v':
			case '\f':
			case '\r':
			case ' ': break;
			default:  lx_abnf_ungetc(lx, c); return lx->z(lx);
			}
			break;

		case S2: /* e.g. "\n" */
			switch ((unsigned char) c) {
			case '\n': state = S17; break;
			default:  lx_abnf_ungetc(lx, c); return lx->z(lx);
			}
			break;

		case S3: /* e.g. "\"" */
			lx_abnf_ungetc(lx, c); return lx->z = z1, lx->z(lx);

		case S4: /* e.g. "%" */
			switch ((unsigned char) c) {
			case 'b': state = S18; break;
			case 'd': state = S19; break;
			case 'i': state = S20; break;
			case 's': state = S21; break;
			case 'x': state = S22; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S5: /* e.g. "(" */
			lx_abnf_ungetc(lx, c); return TOK_STARTGROUP;

		case S6: /* e.g. ")" */
			lx_abnf_ungetc(lx, c); return TOK_ENDGROUP;

		case S7: /* e.g. "*" */
			lx_abnf_ungetc(lx, c); return TOK_REP;

		case S8: /* e.g. "\057" */
			lx_abnf_ungetc(lx, c); return TOK_ALT;

		case S9: /* e.g. "0" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9': break;
			default:  lx_abnf_ungetc(lx, c); return TOK_COUNT;
			}
			break;

		case S10: /* e.g. ";" */
			lx_abnf_ungetc(lx, c); return lx->z = z3, lx->z(lx);

		case S11: /* e.g. "<" */
			lx_abnf_ungetc(lx, c); return lx->z = z2, lx->z(lx);

		case S12: /* e.g. "=" */
			switch ((unsigned char) c) {
			case '/': state = S16; break;
			default:  lx_abnf_ungetc(lx, c); return TOK_EQUALS;
			}
			break;

		case S13: /* e.g. "a" */
			switch ((unsigned char) c) {
			case '-':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z': break;
			default:  lx_abnf_ungetc(lx, c); return TOK_IDENT;
			}
			break;

		case S14: /* e.g. "[" */
			lx_abnf_ungetc(lx, c); return TOK_STARTOPT;

		case S15: /* e.g. "]" */
			lx_abnf_ungetc(lx, c); return TOK_ENDOPT;

		case S16: /* e.g. "=\057" */
			lx_abnf_ungetc(lx, c); return TOK_ALTINC;

		case S17: /* e.g. "\n\n" */
			lx_abnf_ungetc(lx, c); return TOK_SEP;

		case S18: /* e.g. "%b" */
			switch ((unsigned char) c) {
			case '0':
			case '1': state = S34; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S19: /* e.g. "%d" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9': state = S25; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S20: /* e.g. "%i" */
			switch ((unsigned char) c) {
			case '"': state = S3; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S21: /* e.g. "%s" */
			switch ((unsigned char) c) {
			case '"': state = S23; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S22: /* e.g. "%x" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f': state = S24; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S23: /* e.g. "%s\"" */
			lx_abnf_ungetc(lx, c); return lx->z = z0, lx->z(lx);

		case S24: /* e.g. "%xa" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f': break;
			case '-': state = S30; break;
			case '.': state = S31; break;
			default:  lx_abnf_ungetc(lx, c); return TOK_HEXSTR;
			}
			break;

		case S25: /* e.g. "%d0" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9': break;
			case '-': state = S26; break;
			case '.': state = S27; break;
			default:  lx_abnf_ungetc(lx, c); return TOK_DECSTR;
			}
			break;

		case S26: /* e.g. "%d0-" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9': state = S28; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S27: /* e.g. "%d0." */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9': state = S29; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S28: /* e.g. "%d0-0" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9': break;
			default:  lx_abnf_ungetc(lx, c); return TOK_DECRANGE;
			}
			break;

		case S29: /* e.g. "%d0.0" */
			switch ((unsigned char) c) {
			case '.': state = S27; break;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9': break;
			default:  lx_abnf_ungetc(lx, c); return TOK_DECSTR;
			}
			break;

		case S30: /* e.g. "%xa-" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f': state = S33; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S31: /* e.g. "%xa." */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f': state = S32; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S32: /* e.g. "%xa.a" */
			switch ((unsigned char) c) {
			case '.': state = S31; break;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f': break;
			default:  lx_abnf_ungetc(lx, c); return TOK_HEXSTR;
			}
			break;

		case S33: /* e.g. "%xa-a" */
			switch ((unsigned char) c) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f': break;
			default:  lx_abnf_ungetc(lx, c); return TOK_HEXRANGE;
			}
			break;

		case S34: /* e.g. "%b0" */
			switch ((unsigned char) c) {
			case '0':
			case '1': break;
			case '-': state = S35; break;
			case '.': state = S36; break;
			default:  lx_abnf_ungetc(lx, c); return TOK_BINSTR;
			}
			break;

		case S35: /* e.g. "%b0-" */
			switch ((unsigned char) c) {
			case '0':
			case '1': state = S38; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S36: /* e.g. "%b0." */
			switch ((unsigned char) c) {
			case '0':
			case '1': state = S37; break;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
			break;

		case S37: /* e.g. "%b0.0" */
			switch ((unsigned char) c) {
			case '.': state = S36; break;
			case '0':
			case '1': break;
			default:  lx_abnf_ungetc(lx, c); return TOK_BINSTR;
			}
			break;

		case S38: /* e.g. "%b0-0" */
			switch ((unsigned char) c) {
			case '0':
			case '1': break;
			default:  lx_abnf_ungetc(lx, c); return TOK_BINRANGE;
			}
			break;

		default:
			; /* unreached */
		}

		switch (state) {
		case S1:
		case S3:
		case S10:
		case S11:
		case S20:
		case S21:
		case S23:
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx->buf_opaque, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case NONE: return TOK_EOF;
	case S1: return TOK_EOF;
	case S2: return TOK_EOF;
	case S3: return TOK_EOF;
	case S5: return TOK_STARTGROUP;
	case S6: return TOK_ENDGROUP;
	case S7: return TOK_REP;
	case S8: return TOK_ALT;
	case S9: return TOK_COUNT;
	case S10: return TOK_EOF;
	case S11: return TOK_EOF;
	case S12: return TOK_EQUALS;
	case S13: return TOK_IDENT;
	case S14: return TOK_STARTOPT;
	case S15: return TOK_ENDOPT;
	case S16: return TOK_ALTINC;
	case S17: return TOK_SEP;
	case S23: return TOK_EOF;
	case S24: return TOK_HEXSTR;
	case S25: return TOK_DECSTR;
	case S28: return TOK_DECRANGE;
	case S29: return TOK_DECSTR;
	case S32: return TOK_HEXSTR;
	case S33: return TOK_HEXRANGE;
	case S34: return TOK_BINSTR;
	case S37: return TOK_BINSTR;
	case S38: return TOK_BINRANGE;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

const char *
lx_abnf_name(enum lx_abnf_token t)
{
	switch (t) {
	case TOK_ENDOPT: return "ENDOPT";
	case TOK_STARTOPT: return "STARTOPT";
	case TOK_COUNT: return "COUNT";
	case TOK_REP: return "REP";
	case TOK_ENDGROUP: return "ENDGROUP";
	case TOK_STARTGROUP: return "STARTGROUP";
	case TOK_ALTINC: return "ALTINC";
	case TOK_ALT: return "ALT";
	case TOK_CS_LITERAL: return "CS_LITERAL";
	case TOK_CI_LITERAL: return "CI_LITERAL";
	case TOK_HEXRANGE: return "HEXRANGE";
	case TOK_DECRANGE: return "DECRANGE";
	case TOK_BINRANGE: return "BINRANGE";
	case TOK_HEXSTR: return "HEXSTR";
	case TOK_DECSTR: return "DECSTR";
	case TOK_BINSTR: return "BINSTR";
	case TOK_EQUALS: return "EQUALS";
	case TOK_SEP: return "SEP";
	case TOK_CHAR: return "CHAR";
	case TOK_NAME: return "NAME";
	case TOK_IDENT: return "IDENT";
	case TOK_EOF:     return "EOF";
	case TOK_ERROR:   return "ERROR";
	case TOK_UNKNOWN: return "UNKNOWN";
	default: return "?";
	}
}

const char *
lx_abnf_example(enum lx_abnf_token (*z)(struct lx_abnf_lx *), enum lx_abnf_token t)
{
	assert(z != NULL);

	if (z == z0) {
		switch (t) {
		case TOK_CS_LITERAL: return "\"";
		case TOK_CHAR: return "a";
		default: goto error;
		}
	} else
	if (z == z1) {
		switch (t) {
		case TOK_CI_LITERAL: return "\"";
		case TOK_CHAR: return "a";
		default: goto error;
		}
	} else
	if (z == z2) {
		switch (t) {
		case TOK_CHAR: return "a";
		case TOK_NAME: return ">";
		default: goto error;
		}
	} else
	if (z == z3) {
		switch (t) {
		default: goto error;
		}
	} else
	if (z == z4) {
		switch (t) {
		case TOK_ENDOPT: return "]";
		case TOK_STARTOPT: return "[";
		case TOK_COUNT: return "0";
		case TOK_REP: return "*";
		case TOK_ENDGROUP: return ")";
		case TOK_STARTGROUP: return "(";
		case TOK_ALTINC: return "=\057";
		case TOK_ALT: return "\057";
		case TOK_HEXRANGE: return "%xa-a";
		case TOK_DECRANGE: return "%d0-0";
		case TOK_BINRANGE: return "%b0-0";
		case TOK_HEXSTR: return "%xa";
		case TOK_DECSTR: return "%d0";
		case TOK_BINSTR: return "%b0";
		case TOK_EQUALS: return "=";
		case TOK_SEP: return "\n\n";
		case TOK_IDENT: return "a";
		default: goto error;
		}
	}

error:

	errno = EINVAL;
	return NULL;
}

void
lx_abnf_init(struct lx_abnf_lx *lx)
{
	static const struct lx_abnf_lx lx_default;

	assert(lx != NULL);

	*lx = lx_default;

	lx->c = EOF;
	lx->z = z4;

	lx->end.byte = 0;
	lx->end.line = 1;
	lx->end.col  = 1;
}

enum lx_abnf_token
lx_abnf_next(struct lx_abnf_lx *lx)
{
	enum lx_abnf_token t;

	assert(lx != NULL);
	assert(lx->z != NULL);

	if (lx->lgetc == NULL) {
		return TOK_EOF;
	}

	t = lx->z(lx);

	if (lx->push != NULL) {
		if (-1 == lx->push(lx->buf_opaque, '\0')) {
			return TOK_ERROR;
		}
	}

	return t;
}

