
/*
 * Automatically generated by lexi version 2.0
 * Copyright terms for the input source also apply to this generated code.
 */

#include <assert.h>
#include <string.h>

#if defined(__STDC_VERSION__) && (__STDC_VERSION__ - 0L) >= 199901L
#include <stdbool.h>
#include <stdint.h>
#endif



	#include <assert.h>
	#include <stdio.h>
	#include <stdlib.h>

	#include "../io.h"
	#include "../main.h"
	#include "../tokens.h"
	#include "../xalloc.h"

	#include "bnf_lexer.h"

	/*
	 * Interfaces for the generated lexer.
	 */

	typedef enum tok ZTTERMINAL;


	FILE *io_fin;
	unsigned int io_line;

	char io_buffer[1024];

	size_t bufferindex;


	/*
	 * Lexi's interface to get a character from our input stream.
	 */
	static int
	lexi_getchar(struct bnf_state *state)
	{
		int c;

		assert(state != NULL);

		(void) state;

		c = getc(io_fin);
		if (c == EOF) {
			return EOF;
		}

		if (c == '\n') {
			io_line++;
		}

		return c;
	}

int bnf_readchar(struct bnf_state *state) {
	if (state->buffer_index) {
		return bnf_pop(state);
	}

	return lexi_getchar(state);
}
void bnf_push(struct bnf_state *state, const int c) {
	assert(state);
	assert((size_t) state->buffer_index < sizeof state->buffer / sizeof *state->buffer);
	state->buffer[state->buffer_index++] = c;
}

int bnf_pop(struct bnf_state *state) {
	assert(state);
	assert(state->buffer_index > 0);
	return state->buffer[--state->buffer_index];
}

void bnf_flush(struct bnf_state *state) {
	state->buffer_index = 0;
}


/* LOOKUP TABLE */

#if defined(__STDC_VERSION__) && (__STDC_VERSION__ - 0L) >= 199901L
typedef uint8_t lookup_type;
#else
typedef unsigned char lookup_type;
#endif
static lookup_type lookup_tab[] = {
	   0,    0,    0,    0,    0,    0,    0,    0,    0,  0x2,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,  0x2,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,  0x1,    0,    0, 
	 0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,    0,    0, 
	   0,    0,    0,    0,    0,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1, 
	 0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1, 
	 0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,    0,    0,    0,    0,  0x1, 
	   0,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1, 
	 0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1,  0x1, 
	 0x1,  0x1,  0x1,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 
	   0,    0,    0,    0
};

#if defined(__STDC_VERSION__) && (__STDC_VERSION__ - 0L) >= 199901L
bool bnf_group(enum bnf_groups group, int c) {
#else
int bnf_group(enum bnf_groups group, int c) {
#endif
	if (c == LEXI_EOF) {
		return 0;
	}
	return lookup_tab[c] & group;
}


/* PRE-PASS ANALYSERS */

void bnf_init(struct bnf_state *state) {
	state->zone = bnf_next;
	state->buffer_index = 0;
}
/* ZONES PASS ANALYSER PROTOTYPES */

static int bnf_next_double(struct bnf_state *state);
static int bnf_next_single(struct bnf_state *state);
static int bnf_next_name(struct bnf_state *state);
/* MAIN PASS ANALYSERS */


/* MAIN PASS ANALYSER for double */
static int
bnf_next_double(struct bnf_state *state)
{
	start: {
		int c0 = bnf_readchar(state);
		switch (c0) {
		case LEXI_EOF: {
				/* ACTION <err_unexpected_eof> */
				{

	xerror("unexpected EOF on line %d", io_line);
				}
				/* END ACTION <err_unexpected_eof> */
				goto start; /* leaf */
			}

		case '"': {
				/* ACTION <io_literal> */
				{
					ZTTERMINAL ZT1;

	ZT1 = io_literal();
					return ZT1;
				}
				/* END ACTION <io_literal> */
			}

		}

		/* DEFAULT */
		/* ACTION <io_push> */
		{

	io_push(c0);
		}
		/* END ACTION <io_push> */
		goto start; /* DEFAULT */
	}
}

/* MAIN PASS ANALYSER for single */
static int
bnf_next_single(struct bnf_state *state)
{
	start: {
		int c0 = bnf_readchar(state);
		switch (c0) {
		case LEXI_EOF: {
				/* ACTION <err_unexpected_eof> */
				{

	xerror("unexpected EOF on line %d", io_line);
				}
				/* END ACTION <err_unexpected_eof> */
				goto start; /* leaf */
			}

		case '\'': {
				/* ACTION <io_literal> */
				{
					ZTTERMINAL ZT1;

	ZT1 = io_literal();
					return ZT1;
				}
				/* END ACTION <io_literal> */
			}

		}

		/* DEFAULT */
		/* ACTION <io_push> */
		{

	io_push(c0);
		}
		/* END ACTION <io_push> */
		goto start; /* DEFAULT */
	}
}

/* MAIN PASS ANALYSER for name */
static int
bnf_next_name(struct bnf_state *state)
{
	start: {
		int c0 = bnf_readchar(state);
		switch (c0) {
		case LEXI_EOF: {
				/* ACTION <err_unexpected_eof> */
				{

	xerror("unexpected EOF on line %d", io_line);
				}
				/* END ACTION <err_unexpected_eof> */
				goto start; /* leaf */
			}

		case '>': {
				return tok_name;
			}

		}
		if (bnf_group(bnf_group_character, c0)) {
			/* ACTION <io_push> */
			{

	io_push(c0);
			}
			/* END ACTION <io_push> */
			goto start; /* leaf */
		}

		/* DEFAULT */
		/* ACTION <err_unexpected_character> */
		{

	xerror("unexpected character \"%c\" on line %d", c0, io_line);
		}
		/* END ACTION <err_unexpected_character> */
		goto start; /* DEFAULT */
	}
}

/* MAIN PASS ANALYSER for global zone */
int
bnf_next(struct bnf_state *state)
{
	if (state->zone != bnf_next)
		return state->zone(state);
	start: {
		int c0 = bnf_readchar(state);
		if (bnf_group(bnf_group_white, c0)) goto start;
		switch (c0) {
		case '"': {
				return bnf_next_double(state);
			}

		case '\'': {
				return bnf_next_single(state);
			}

		case '<': {
				return bnf_next_name(state);
			}

		case '\n': {
				int c1 = bnf_readchar(state);
				if (c1 == '\n') {
					return tok_sep;
				}
				bnf_push(state, c1);
				goto start; /* leaf */
			}

		case LEXI_EOF: {
				return tok_sep;
			}

		case '|': {
				return tok_alt;
			}

		case ':': {
				int c1 = bnf_readchar(state);
				if (c1 == ':') {
					int c2 = bnf_readchar(state);
					if (c2 == '=') {
						return tok_equals;
					}
					bnf_push(state, c2);
				}
				bnf_push(state, c1);
			}
			break;

		}

		/* DEFAULT */
		/* ACTION <err_unexpected_character> */
		{

	xerror("unexpected character \"%c\" on line %d", c0, io_line);
		}
		/* END ACTION <err_unexpected_character> */
		goto start; /* DEFAULT */
	}
}



