/* Generated by lx */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include <unistd.h>
#include <fcntl.h>

#include LX_HEADER

static enum lx_bnf_token z1(struct lx_bnf_lx *lx);
static enum lx_bnf_token z2(struct lx_bnf_lx *lx);
static enum lx_bnf_token z3(struct lx_bnf_lx *lx);
static enum lx_bnf_token z4(struct lx_bnf_lx *lx);

static int
lx_getc(struct lx_bnf_lx *lx)
{
	int c;

	assert(lx != NULL);
	assert(lx->lgetc != NULL);

	if (lx->c != EOF) {
		c = lx->c, lx->c = EOF;
	} else {
		c = lx->lgetc(lx);
		if (c == EOF) {
			return EOF;
		}
	}

	lx->end.byte++;
	lx->end.col++;

	if (c == '\n') {
		lx->end.line++;
		lx->end.col = 1;
	}

	return c;
}

static void
lx_bnf_ungetc(struct lx_bnf_lx *lx, int c)
{
	assert(lx != NULL);
	assert(lx->c == EOF);

	lx->c = c;

	if (lx->pop != NULL) {
		lx->pop(lx);
	}

	lx->end.byte--;
	lx->end.col--;

	if (c == '\n') {
		lx->end.line--;
		lx->end.col = 0; /* XXX: lost information */
	}
}

int
lx_bnf_fgetc(struct lx_bnf_lx *lx)
{
	assert(lx != NULL);
	assert(lx->opaque != NULL);

	return fgetc(lx->opaque);
}

int
lx_bnf_sgetc(struct lx_bnf_lx *lx)
{
	char *s;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	s = lx->opaque;
	if (*s == '\0') {
		return EOF;
	}

	return lx->opaque = s + 1, *s;
}

int
lx_bnf_agetc(struct lx_bnf_lx *lx)
{
	struct lx_arr *a;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	a = lx->opaque;

	assert(a != NULL);
	assert(a->p != NULL);

	if (a->len == 0) {
		return EOF;
	}

	return a->len--, *a->p++;
}

int
lx_bnf_dgetc(struct lx_bnf_lx *lx)
{
	struct lx_fd *d;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	d = lx->opaque;
	assert(d->fd != -1);
	assert(d->p != NULL);

	if (d->len == 0) {
		ssize_t r;

		assert((fcntl(d->fd, F_GETFL) & O_NONBLOCK) == 0);

		d->p = (char *) d + sizeof *d;

		r = read(d->fd, d->p, d->bufsz);
		if (r == -1) {
			assert(errno != EAGAIN);
			return EOF;
		}

		if (r == 0) {
			return EOF;
		}

		d->len = r;
	}

	return d->len--, *d->p++;
}

int
lx_bnf_dynpush(struct lx_bnf_lx *lx, char c)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);
	assert(c != EOF);

	t = lx->buf;

	assert(t != NULL);

	if (t->p == t->a + t->len) {
		size_t len;
		char *tmp;

		if (t->len == 0) {
			assert(LX_DYN_LOW > 0);
			len = LX_DYN_LOW;
		} else {
			len = t->len * LX_DYN_FACTOR;
			if (len < t->len) {
				errno = ERANGE;
				return -1;
			}
		}

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->p   = tmp + (t->p - t->a);
		t->a   = tmp;
		t->len = len;
	}

	assert(t->p != NULL);
	assert(t->a != NULL);

	*t->p++ = c;

	return 0;
}

void
lx_bnf_dynpop(struct lx_bnf_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->a != NULL);
	assert(t->p >= t->a);

	if (t->p == t->a) {
		return;
	}

	t->p--;
}

int
lx_bnf_dynclear(struct lx_bnf_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	if (t->len > LX_DYN_HIGH) {
		size_t len;
		char *tmp;

		len = t->len / LX_DYN_FACTOR;

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->a   = tmp;
		t->len = len;
	}

	t->p = t->a;

	return 0;
}

void
lx_bnf_dynfree(struct lx_bnf_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	free(t->a);
}
int
lx_bnf_fixedpush(struct lx_bnf_lx *lx, char c)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);
	assert(c != EOF);

	t = lx->buf;

	assert(t != NULL);
	assert(t->p != NULL);
	assert(t->a != NULL);

	if (t->p == t->a + t->len) {
		errno = ENOMEM;
		return -1;
	}

	*t->p++ = c;

	return 0;
}

void
lx_bnf_fixedpop(struct lx_bnf_lx *lx)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->a != NULL);
	assert(t->p >= t->a);

	if (t->p == t->a) {
		return;
	}

	t->p--;
}

int
lx_bnf_fixedclear(struct lx_bnf_lx *lx)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->p != NULL);
	assert(t->a != NULL);

	t->p = t->a;

	return 0;
}

static enum lx_bnf_token
z1(struct lx_bnf_lx *lx)
{
	int c;

	enum {
		S1, S2, S3
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S3;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. "\"" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return lx->z = z4, TOK_LITERAL;
			}

		case S2: /* e.g. "a" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return TOK_CHAR;
			}

		case S3: /* start */
			switch (c) {
			case '\"': state = S1;      continue;
			default:  state = S2;     continue;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_LITERAL;
	case S2: return TOK_CHAR;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_bnf_token
z2(struct lx_bnf_lx *lx)
{
	int c;

	enum {
		S1, S2, S3
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S3;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. "'" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return lx->z = z4, TOK_LITERAL;
			}

		case S2: /* e.g. "a" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return TOK_CHAR;
			}

		case S3: /* start */
			switch (c) {
			case '\'': state = S1;      continue;
			default:  state = S2;     continue;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_LITERAL;
	case S2: return TOK_CHAR;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_bnf_token
z3(struct lx_bnf_lx *lx)
{
	int c;

	enum {
		S1, S2, S3
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S3;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. ">" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return lx->z = z4, TOK_NAME;
			}

		case S2: /* e.g. "a" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return TOK_CHAR;
			}

		case S3: /* start */
			switch (c) {
			case '-': state = S2;      continue;
			case '0': state = S2;      continue;
			case '1': state = S2;      continue;
			case '2': state = S2;      continue;
			case '3': state = S2;      continue;
			case '4': state = S2;      continue;
			case '5': state = S2;      continue;
			case '6': state = S2;      continue;
			case '7': state = S2;      continue;
			case '8': state = S2;      continue;
			case '9': state = S2;      continue;
			case '>': state = S1;      continue;
			case 'A': state = S2;      continue;
			case 'B': state = S2;      continue;
			case 'C': state = S2;      continue;
			case 'D': state = S2;      continue;
			case 'E': state = S2;      continue;
			case 'F': state = S2;      continue;
			case 'G': state = S2;      continue;
			case 'H': state = S2;      continue;
			case 'I': state = S2;      continue;
			case 'J': state = S2;      continue;
			case 'K': state = S2;      continue;
			case 'L': state = S2;      continue;
			case 'M': state = S2;      continue;
			case 'N': state = S2;      continue;
			case 'O': state = S2;      continue;
			case 'P': state = S2;      continue;
			case 'Q': state = S2;      continue;
			case 'R': state = S2;      continue;
			case 'S': state = S2;      continue;
			case 'T': state = S2;      continue;
			case 'U': state = S2;      continue;
			case 'V': state = S2;      continue;
			case 'W': state = S2;      continue;
			case 'X': state = S2;      continue;
			case 'Y': state = S2;      continue;
			case 'Z': state = S2;      continue;
			case '_': state = S2;      continue;
			case 'a': state = S2;      continue;
			case 'b': state = S2;      continue;
			case 'c': state = S2;      continue;
			case 'd': state = S2;      continue;
			case 'e': state = S2;      continue;
			case 'f': state = S2;      continue;
			case 'g': state = S2;      continue;
			case 'h': state = S2;      continue;
			case 'i': state = S2;      continue;
			case 'j': state = S2;      continue;
			case 'k': state = S2;      continue;
			case 'l': state = S2;      continue;
			case 'm': state = S2;      continue;
			case 'n': state = S2;      continue;
			case 'o': state = S2;      continue;
			case 'p': state = S2;      continue;
			case 'q': state = S2;      continue;
			case 'r': state = S2;      continue;
			case 's': state = S2;      continue;
			case 't': state = S2;      continue;
			case 'u': state = S2;      continue;
			case 'v': state = S2;      continue;
			case 'w': state = S2;      continue;
			case 'x': state = S2;      continue;
			case 'y': state = S2;      continue;
			case 'z': state = S2;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_NAME;
	case S2: return TOK_CHAR;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_bnf_token
z4(struct lx_bnf_lx *lx)
{
	int c;

	enum {
		S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, 
		S11, S12
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S12;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
		case S6:
		case S10:
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. "::=" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return TOK_EQUALS;
			}

		case S2: /* e.g. "::" */
			switch (c) {
			case '=': state = S1;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S3: /* e.g. "''" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return TOK_EMPTY;
			}

		case S4: /* e.g. "\x0a\x0a" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return TOK_SEP;
			}

		case S5: /* e.g. "\x0a" */
			switch (c) {
			case '\n': state = S4;      continue;
			default:  lx_bnf_ungetc(lx, c); return lx->z(lx);
			}

		case S6: /* e.g. "\x09" */
			switch (c) {
			case '\t':	          continue;
			case '\v':	          continue;
			case '\f':	          continue;
			case '\r':	          continue;
			case ' ':	          continue;
			default:  lx_bnf_ungetc(lx, c); return lx->z(lx);
			}

		case S7: /* e.g. "\"" */
			switch (c) {
			case '\"': state = S3;      continue;
			default:  lx_bnf_ungetc(lx, c); return lx->z = z1, lx->z(lx);
			}

		case S8: /* e.g. "'" */
			switch (c) {
			case '\'': state = S3;      continue;
			default:  lx_bnf_ungetc(lx, c); return lx->z = z2, lx->z(lx);
			}

		case S9: /* e.g. ":" */
			switch (c) {
			case ':': state = S2;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S10: /* e.g. "<" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return lx->z = z3, lx->z(lx);
			}

		case S11: /* e.g. "|" */
			switch (c) {
			default:  lx_bnf_ungetc(lx, c); return TOK_ALT;
			}

		case S12: /* start */
			switch (c) {
			case '\t': state = S6;      continue;
			case '\n': state = S5;      continue;
			case '\v': state = S6;      continue;
			case '\f': state = S6;      continue;
			case '\r': state = S6;      continue;
			case ' ': state = S6;      continue;
			case '\"': state = S7;      continue;
			case '\'': state = S8;      continue;
			case ':': state = S9;      continue;
			case '<': state = S10;      continue;
			case '|': state = S11;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_EQUALS;
	case S3: return TOK_EMPTY;
	case S4: return TOK_SEP;
	case S5: return TOK_EOF;
	case S6: return TOK_EOF;
	case S7: return TOK_EOF;
	case S8: return TOK_EOF;
	case S10: return TOK_EOF;
	case S11: return TOK_ALT;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

const char *
lx_bnf_name(enum lx_bnf_token t)
{
	switch (t) {
	case TOK_EMPTY: return "EMPTY";
	case TOK_LITERAL: return "LITERAL";
	case TOK_NAME: return "NAME";
	case TOK_CHAR: return "CHAR";
	case TOK_SEP: return "SEP";
	case TOK_ALT: return "ALT";
	case TOK_EQUALS: return "EQUALS";
	case TOK_EOF:     return "EOF";
	case TOK_ERROR:   return "ERROR";
	case TOK_UNKNOWN: return "UNKNOWN";
	default: return "?";
	}
}

const char *
lx_bnf_example(enum lx_bnf_token (*z)(struct lx_bnf_lx *), enum lx_bnf_token t)
{
	assert(z != NULL);

	if (z == z1) {
		switch (t) {
		case TOK_LITERAL: return "\"";
		case TOK_CHAR: return "a";
		default: goto error;
		}
	} else
	if (z == z2) {
		switch (t) {
		case TOK_LITERAL: return "'";
		case TOK_CHAR: return "a";
		default: goto error;
		}
	} else
	if (z == z3) {
		switch (t) {
		case TOK_NAME: return ">";
		case TOK_CHAR: return "a";
		default: goto error;
		}
	} else
	if (z == z4) {
		switch (t) {
		case TOK_EMPTY: return "''";
		case TOK_SEP: return "\x0a\x0a";
		case TOK_ALT: return "|";
		case TOK_EQUALS: return "::=";
		default: goto error;
		}
	}

error:

	errno = EINVAL;
	return NULL;
}

void
lx_bnf_init(struct lx_bnf_lx *lx)
{
	static const struct lx_bnf_lx lx_default;

	assert(lx != NULL);

	*lx = lx_default;

	lx->c = EOF;
	lx->z = NULL;

	lx->end.byte = 0;
	lx->end.line = 1;
	lx->end.col  = 1;
}

enum lx_bnf_token
lx_bnf_next(struct lx_bnf_lx *lx)
{
	enum lx_bnf_token t;

	assert(lx != NULL);

	if (lx->lgetc == NULL) {
		return TOK_EOF;
	}

	if (lx->z == NULL) {
		lx->z = z4;
	}

	t = lx->z(lx);

	if (lx->push != NULL) {
		if (-1 == lx->push(lx, '\0')) {
			return TOK_ERROR;
		}
	}

	if (lx->lgetc == NULL && lx->free != NULL) {
		lx->free(lx);
	}

	return t;
}

