(* transcribed from http://json.org *)

object
	= '{', [ string, ':', value, { ',', string, ':', value } ], '}' ;

array
	= '[', [ value, { ',', value } ], ']' ;

value
	= string
	| number
	| object
	| array
	| 'true'
	| 'false'
	| 'null'
	;

string
	= '"', {
		char
		| '\', ( '"' | '\' | '/' | 'b' | 'f' | 'n' | 'r' | 't' | 'u', hex )
	}, '"' ;

number = [ "-" ], ( "0" | digit 1-9, { digit } ), [ ".", { digit } ], [ ( "e" | "E" ), [ "+" | "-" ], { digit } ] ;

