/* Generated by lx */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include <unistd.h>
#include <fcntl.h>

#include LX_HEADER

static enum lx_rbnf_token z1(struct lx_rbnf_lx *lx);
static enum lx_rbnf_token z2(struct lx_rbnf_lx *lx);

static int
lx_getc(struct lx_rbnf_lx *lx)
{
	int c;

	assert(lx != NULL);
	assert(lx->lgetc != NULL);

	if (lx->c != EOF) {
		c = lx->c, lx->c = EOF;
	} else {
		c = lx->lgetc(lx);
		if (c == EOF) {
			return EOF;
		}
	}

	lx->end.byte++;
	lx->end.col++;

	if (c == '\n') {
		lx->end.line++;
		lx->end.col = 1;
	}

	return c;
}

static void
lx_rbnf_ungetc(struct lx_rbnf_lx *lx, int c)
{
	assert(lx != NULL);
	assert(lx->c == EOF);

	lx->c = c;

	if (lx->pop != NULL) {
		lx->pop(lx);
	}

	lx->end.byte--;
	lx->end.col--;

	if (c == '\n') {
		lx->end.line--;
		lx->end.col = 0; /* XXX: lost information */
	}
}

int
lx_rbnf_fgetc(struct lx_rbnf_lx *lx)
{
	assert(lx != NULL);
	assert(lx->opaque != NULL);

	return fgetc(lx->opaque);
}

int
lx_rbnf_sgetc(struct lx_rbnf_lx *lx)
{
	char *s;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	s = lx->opaque;
	if (*s == '\0') {
		return EOF;
	}

	return lx->opaque = s + 1, *s;
}

int
lx_rbnf_agetc(struct lx_rbnf_lx *lx)
{
	struct lx_arr *a;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	a = lx->opaque;

	assert(a != NULL);
	assert(a->p != NULL);

	if (a->len == 0) {
		return EOF;
	}

	return a->len--, *a->p++;
}

int
lx_rbnf_dgetc(struct lx_rbnf_lx *lx)
{
	struct lx_fd *d;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	d = lx->opaque;
	assert(d->fd != -1);
	assert(d->p != NULL);

	if (d->len == 0) {
		ssize_t r;

		assert((fcntl(d->fd, F_GETFL) & O_NONBLOCK) == 0);

		d->p = (char *) d + sizeof *d;

		r = read(d->fd, d->p, d->bufsz);
		if (r == -1) {
			assert(errno != EAGAIN);
			return EOF;
		}

		if (r == 0) {
			return EOF;
		}

		d->len = r;
	}

	return d->len--, *d->p++;
}

int
lx_rbnf_dynpush(struct lx_rbnf_lx *lx, char c)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);
	assert(c != EOF);

	t = lx->buf;

	assert(t != NULL);

	if (t->p == t->a + t->len) {
		size_t len;
		char *tmp;

		if (t->len == 0) {
			assert(LX_DYN_LOW > 0);
			len = LX_DYN_LOW;
		} else {
			len = t->len * LX_DYN_FACTOR;
			if (len < t->len) {
				errno = ERANGE;
				return -1;
			}
		}

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->p   = tmp + (t->p - t->a);
		t->a   = tmp;
		t->len = len;
	}

	assert(t->p != NULL);
	assert(t->a != NULL);

	*t->p++ = c;

	return 0;
}

void
lx_rbnf_dynpop(struct lx_rbnf_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->a != NULL);
	assert(t->p >= t->a);

	if (t->p == t->a) {
		return;
	}

	t->p--;
}

int
lx_rbnf_dynclear(struct lx_rbnf_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	if (t->len > LX_DYN_HIGH) {
		size_t len;
		char *tmp;

		len = t->len / LX_DYN_FACTOR;

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->a   = tmp;
		t->len = len;
	}

	t->p = t->a;

	return 0;
}

void
lx_rbnf_dynfree(struct lx_rbnf_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	free(t->a);
}
int
lx_rbnf_fixedpush(struct lx_rbnf_lx *lx, char c)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);
	assert(c != EOF);

	t = lx->buf;

	assert(t != NULL);
	assert(t->p != NULL);
	assert(t->a != NULL);

	if (t->p == t->a + t->len) {
		errno = ENOMEM;
		return -1;
	}

	*t->p++ = c;

	return 0;
}

void
lx_rbnf_fixedpop(struct lx_rbnf_lx *lx)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->a != NULL);
	assert(t->p >= t->a);

	if (t->p == t->a) {
		return;
	}

	t->p--;
}

int
lx_rbnf_fixedclear(struct lx_rbnf_lx *lx)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->p != NULL);
	assert(t->a != NULL);

	t->p = t->a;

	return 0;
}

static enum lx_rbnf_token
z1(struct lx_rbnf_lx *lx)
{
	int c;

	enum {
		S1, S2, S3
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S3;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. ">" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return lx->z = z2, TOK_NAME;
			}

		case S2: /* e.g. "a" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_CHAR;
			}

		case S3: /* start */
			switch (c) {
			case '\x0': state = S2;      continue;
			case '\x1': state = S2;      continue;
			case '\x2': state = S2;      continue;
			case '\x3': state = S2;      continue;
			case '\x4': state = S2;      continue;
			case '\x5': state = S2;      continue;
			case '\x6': state = S2;      continue;
			case '\x7': state = S2;      continue;
			case '\x8': state = S2;      continue;
			case '\xe': state = S2;      continue;
			case '\xf': state = S2;      continue;
			case '\x10': state = S2;      continue;
			case '\x11': state = S2;      continue;
			case '\x12': state = S2;      continue;
			case '\x13': state = S2;      continue;
			case '\x14': state = S2;      continue;
			case '\x15': state = S2;      continue;
			case '\x16': state = S2;      continue;
			case '\x17': state = S2;      continue;
			case '\x18': state = S2;      continue;
			case '\x19': state = S2;      continue;
			case '\x1a': state = S2;      continue;
			case '\x1b': state = S2;      continue;
			case '\x1c': state = S2;      continue;
			case '\x1d': state = S2;      continue;
			case '\x1e': state = S2;      continue;
			case '\x1f': state = S2;      continue;
			case ' ': state = S2;      continue;
			case '!': state = S2;      continue;
			case '\"': state = S2;      continue;
			case '#': state = S2;      continue;
			case '$': state = S2;      continue;
			case '%': state = S2;      continue;
			case '&': state = S2;      continue;
			case '\'': state = S2;      continue;
			case '(': state = S2;      continue;
			case ')': state = S2;      continue;
			case '*': state = S2;      continue;
			case '+': state = S2;      continue;
			case ',': state = S2;      continue;
			case '-': state = S2;      continue;
			case '.': state = S2;      continue;
			case '/': state = S2;      continue;
			case '0': state = S2;      continue;
			case '1': state = S2;      continue;
			case '2': state = S2;      continue;
			case '3': state = S2;      continue;
			case '4': state = S2;      continue;
			case '5': state = S2;      continue;
			case '6': state = S2;      continue;
			case '7': state = S2;      continue;
			case '8': state = S2;      continue;
			case '9': state = S2;      continue;
			case ':': state = S2;      continue;
			case ';': state = S2;      continue;
			case '<': state = S2;      continue;
			case '=': state = S2;      continue;
			case '>': state = S1;      continue;
			case '?': state = S2;      continue;
			case '@': state = S2;      continue;
			case 'A': state = S2;      continue;
			case 'B': state = S2;      continue;
			case 'C': state = S2;      continue;
			case 'D': state = S2;      continue;
			case 'E': state = S2;      continue;
			case 'F': state = S2;      continue;
			case 'G': state = S2;      continue;
			case 'H': state = S2;      continue;
			case 'I': state = S2;      continue;
			case 'J': state = S2;      continue;
			case 'K': state = S2;      continue;
			case 'L': state = S2;      continue;
			case 'M': state = S2;      continue;
			case 'N': state = S2;      continue;
			case 'O': state = S2;      continue;
			case 'P': state = S2;      continue;
			case 'Q': state = S2;      continue;
			case 'R': state = S2;      continue;
			case 'S': state = S2;      continue;
			case 'T': state = S2;      continue;
			case 'U': state = S2;      continue;
			case 'V': state = S2;      continue;
			case 'W': state = S2;      continue;
			case 'X': state = S2;      continue;
			case 'Y': state = S2;      continue;
			case 'Z': state = S2;      continue;
			case '[': state = S2;      continue;
			case '\\': state = S2;      continue;
			case ']': state = S2;      continue;
			case '^': state = S2;      continue;
			case '_': state = S2;      continue;
			case '`': state = S2;      continue;
			case 'a': state = S2;      continue;
			case 'b': state = S2;      continue;
			case 'c': state = S2;      continue;
			case 'd': state = S2;      continue;
			case 'e': state = S2;      continue;
			case 'f': state = S2;      continue;
			case 'g': state = S2;      continue;
			case 'h': state = S2;      continue;
			case 'i': state = S2;      continue;
			case 'j': state = S2;      continue;
			case 'k': state = S2;      continue;
			case 'l': state = S2;      continue;
			case 'm': state = S2;      continue;
			case 'n': state = S2;      continue;
			case 'o': state = S2;      continue;
			case 'p': state = S2;      continue;
			case 'q': state = S2;      continue;
			case 'r': state = S2;      continue;
			case 's': state = S2;      continue;
			case 't': state = S2;      continue;
			case 'u': state = S2;      continue;
			case 'v': state = S2;      continue;
			case 'w': state = S2;      continue;
			case 'x': state = S2;      continue;
			case 'y': state = S2;      continue;
			case 'z': state = S2;      continue;
			case '{': state = S2;      continue;
			case '|': state = S2;      continue;
			case '}': state = S2;      continue;
			case '~': state = S2;      continue;
			case '\x7f': state = S2;      continue;
			case '\x80': state = S2;      continue;
			case '\x81': state = S2;      continue;
			case '\x82': state = S2;      continue;
			case '\x83': state = S2;      continue;
			case '\x84': state = S2;      continue;
			case '\x85': state = S2;      continue;
			case '\x86': state = S2;      continue;
			case '\x87': state = S2;      continue;
			case '\x88': state = S2;      continue;
			case '\x89': state = S2;      continue;
			case '\x8a': state = S2;      continue;
			case '\x8b': state = S2;      continue;
			case '\x8c': state = S2;      continue;
			case '\x8d': state = S2;      continue;
			case '\x8e': state = S2;      continue;
			case '\x8f': state = S2;      continue;
			case '\x90': state = S2;      continue;
			case '\x91': state = S2;      continue;
			case '\x92': state = S2;      continue;
			case '\x93': state = S2;      continue;
			case '\x94': state = S2;      continue;
			case '\x95': state = S2;      continue;
			case '\x96': state = S2;      continue;
			case '\x97': state = S2;      continue;
			case '\x98': state = S2;      continue;
			case '\x99': state = S2;      continue;
			case '\x9a': state = S2;      continue;
			case '\x9b': state = S2;      continue;
			case '\x9c': state = S2;      continue;
			case '\x9d': state = S2;      continue;
			case '\x9e': state = S2;      continue;
			case '\x9f': state = S2;      continue;
			case '\xa0': state = S2;      continue;
			case '\xa1': state = S2;      continue;
			case '\xa2': state = S2;      continue;
			case '\xa3': state = S2;      continue;
			case '\xa4': state = S2;      continue;
			case '\xa5': state = S2;      continue;
			case '\xa6': state = S2;      continue;
			case '\xa7': state = S2;      continue;
			case '\xa8': state = S2;      continue;
			case '\xa9': state = S2;      continue;
			case '\xaa': state = S2;      continue;
			case '\xab': state = S2;      continue;
			case '\xac': state = S2;      continue;
			case '\xad': state = S2;      continue;
			case '\xae': state = S2;      continue;
			case '\xaf': state = S2;      continue;
			case '\xb0': state = S2;      continue;
			case '\xb1': state = S2;      continue;
			case '\xb2': state = S2;      continue;
			case '\xb3': state = S2;      continue;
			case '\xb4': state = S2;      continue;
			case '\xb5': state = S2;      continue;
			case '\xb6': state = S2;      continue;
			case '\xb7': state = S2;      continue;
			case '\xb8': state = S2;      continue;
			case '\xb9': state = S2;      continue;
			case '\xba': state = S2;      continue;
			case '\xbb': state = S2;      continue;
			case '\xbc': state = S2;      continue;
			case '\xbd': state = S2;      continue;
			case '\xbe': state = S2;      continue;
			case '\xbf': state = S2;      continue;
			case '\xc0': state = S2;      continue;
			case '\xc1': state = S2;      continue;
			case '\xc2': state = S2;      continue;
			case '\xc3': state = S2;      continue;
			case '\xc4': state = S2;      continue;
			case '\xc5': state = S2;      continue;
			case '\xc6': state = S2;      continue;
			case '\xc7': state = S2;      continue;
			case '\xc8': state = S2;      continue;
			case '\xc9': state = S2;      continue;
			case '\xca': state = S2;      continue;
			case '\xcb': state = S2;      continue;
			case '\xcc': state = S2;      continue;
			case '\xcd': state = S2;      continue;
			case '\xce': state = S2;      continue;
			case '\xcf': state = S2;      continue;
			case '\xd0': state = S2;      continue;
			case '\xd1': state = S2;      continue;
			case '\xd2': state = S2;      continue;
			case '\xd3': state = S2;      continue;
			case '\xd4': state = S2;      continue;
			case '\xd5': state = S2;      continue;
			case '\xd6': state = S2;      continue;
			case '\xd7': state = S2;      continue;
			case '\xd8': state = S2;      continue;
			case '\xd9': state = S2;      continue;
			case '\xda': state = S2;      continue;
			case '\xdb': state = S2;      continue;
			case '\xdc': state = S2;      continue;
			case '\xdd': state = S2;      continue;
			case '\xde': state = S2;      continue;
			case '\xdf': state = S2;      continue;
			case '\xe0': state = S2;      continue;
			case '\xe1': state = S2;      continue;
			case '\xe2': state = S2;      continue;
			case '\xe3': state = S2;      continue;
			case '\xe4': state = S2;      continue;
			case '\xe5': state = S2;      continue;
			case '\xe6': state = S2;      continue;
			case '\xe7': state = S2;      continue;
			case '\xe8': state = S2;      continue;
			case '\xe9': state = S2;      continue;
			case '\xea': state = S2;      continue;
			case '\xeb': state = S2;      continue;
			case '\xec': state = S2;      continue;
			case '\xed': state = S2;      continue;
			case '\xee': state = S2;      continue;
			case '\xef': state = S2;      continue;
			case '\xf0': state = S2;      continue;
			case '\xf1': state = S2;      continue;
			case '\xf2': state = S2;      continue;
			case '\xf3': state = S2;      continue;
			case '\xf4': state = S2;      continue;
			case '\xf5': state = S2;      continue;
			case '\xf6': state = S2;      continue;
			case '\xf7': state = S2;      continue;
			case '\xf8': state = S2;      continue;
			case '\xf9': state = S2;      continue;
			case '\xfa': state = S2;      continue;
			case '\xfb': state = S2;      continue;
			case '\xfc': state = S2;      continue;
			case '\xfd': state = S2;      continue;
			case '\xfe': state = S2;      continue;
			case '\xff': state = S2;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_NAME;
	case S2: return TOK_CHAR;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_rbnf_token
z2(struct lx_rbnf_lx *lx)
{
	int c;

	enum {
		S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, 
		S11, S12, S13, S14, S15, S16
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S16;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
		case S7:
		case S12:
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. "::=" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_EQUALS;
			}

		case S2: /* e.g. "::" */
			switch (c) {
			case '=': state = S1;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S3: /* e.g. "..." */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_REP;
			}

		case S4: /* e.g. ".." */
			switch (c) {
			case '.': state = S3;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S5: /* e.g. "\x0a\x0a" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_SEP;
			}

		case S6: /* e.g. "\x0a" */
			switch (c) {
			case '\n': state = S5;      continue;
			default:  lx_rbnf_ungetc(lx, c); return lx->z(lx);
			}

		case S7: /* e.g. "\x09" */
			switch (c) {
			case '\t':	          continue;
			case '\v':	          continue;
			case '\f':	          continue;
			case '\r':	          continue;
			case ' ':	          continue;
			default:  lx_rbnf_ungetc(lx, c); return lx->z(lx);
			}

		case S8: /* e.g. "(" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_STARTGROUP;
			}

		case S9: /* e.g. ")" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_ENDGROUP;
			}

		case S10: /* e.g. "." */
			switch (c) {
			case '.': state = S4;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S11: /* e.g. ":" */
			switch (c) {
			case ':': state = S2;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S12: /* e.g. "<" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return lx->z = z1, lx->z(lx);
			}

		case S13: /* e.g. "[" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_STARTOPT;
			}

		case S14: /* e.g. "]" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_ENDOPT;
			}

		case S15: /* e.g. "|" */
			switch (c) {
			default:  lx_rbnf_ungetc(lx, c); return TOK_ALT;
			}

		case S16: /* start */
			switch (c) {
			case '\t': state = S7;      continue;
			case '\n': state = S6;      continue;
			case '\v': state = S7;      continue;
			case '\f': state = S7;      continue;
			case '\r': state = S7;      continue;
			case ' ': state = S7;      continue;
			case '(': state = S8;      continue;
			case ')': state = S9;      continue;
			case '.': state = S10;      continue;
			case ':': state = S11;      continue;
			case '<': state = S12;      continue;
			case '[': state = S13;      continue;
			case ']': state = S14;      continue;
			case '|': state = S15;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_EQUALS;
	case S3: return TOK_REP;
	case S5: return TOK_SEP;
	case S6: return TOK_EOF;
	case S7: return TOK_EOF;
	case S8: return TOK_STARTGROUP;
	case S9: return TOK_ENDGROUP;
	case S12: return TOK_EOF;
	case S13: return TOK_STARTOPT;
	case S14: return TOK_ENDOPT;
	case S15: return TOK_ALT;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

const char *
lx_rbnf_name(enum lx_rbnf_token t)
{
	switch (t) {
	case TOK_ENDGROUP: return "ENDGROUP";
	case TOK_STARTGROUP: return "STARTGROUP";
	case TOK_REP: return "REP";
	case TOK_ALT: return "ALT";
	case TOK_ENDOPT: return "ENDOPT";
	case TOK_STARTOPT: return "STARTOPT";
	case TOK_SEP: return "SEP";
	case TOK_NAME: return "NAME";
	case TOK_CHAR: return "CHAR";
	case TOK_EQUALS: return "EQUALS";
	case TOK_EOF:     return "EOF";
	case TOK_ERROR:   return "ERROR";
	case TOK_UNKNOWN: return "UNKNOWN";
	default: return "?";
	}
}

const char *
lx_rbnf_example(enum lx_rbnf_token (*z)(struct lx_rbnf_lx *), enum lx_rbnf_token t)
{
	assert(z != NULL);

	if (z == z1) {
		switch (t) {
		case TOK_NAME: return ">";
		case TOK_CHAR: return "a";
		default: goto error;
		}
	} else
	if (z == z2) {
		switch (t) {
		case TOK_ENDGROUP: return ")";
		case TOK_STARTGROUP: return "(";
		case TOK_REP: return "...";
		case TOK_ALT: return "|";
		case TOK_ENDOPT: return "]";
		case TOK_STARTOPT: return "[";
		case TOK_SEP: return "\x0a\x0a";
		case TOK_EQUALS: return "::=";
		default: goto error;
		}
	}

error:

	errno = EINVAL;
	return NULL;
}

void
lx_rbnf_init(struct lx_rbnf_lx *lx)
{
	static const struct lx_rbnf_lx lx_default;

	assert(lx != NULL);

	*lx = lx_default;

	lx->c = EOF;
	lx->z = NULL;

	lx->end.byte = 0;
	lx->end.line = 1;
	lx->end.col  = 1;
}

enum lx_rbnf_token
lx_rbnf_next(struct lx_rbnf_lx *lx)
{
	enum lx_rbnf_token t;

	assert(lx != NULL);

	if (lx->lgetc == NULL) {
		return TOK_EOF;
	}

	if (lx->z == NULL) {
		lx->z = z2;
	}

	t = lx->z(lx);

	if (lx->push != NULL) {
		if (-1 == lx->push(lx, '\0')) {
			return TOK_ERROR;
		}
	}

	if (lx->lgetc == NULL && lx->free != NULL) {
		lx->free(lx);
	}

	return t;
}

